### ISSUE TITLE
No pomodoro count & Autostart after break can't be avoided

### ISSUE THREAD

**Issue by firtek** [gfreeau/cinnamon-pomodoro#27]
My pomodoro count doesn't get increased in the Menu under "Completed" but initial counter displays me a big break after 4 pomodoro so it is just a graphical issue in the menu.

Also I have unchecked "Auto start a new pomodoro after the break ends" but still it autostarts after the break.

**Comment by andralexxx** [comment]
Same issue for me.
I'm using LM17 and pomodoro starts ticking randomly after I stopped it. Another problem when I trying to reset Timer it continue countdown.

**Comment by gfreeau** [comment]
Can you provide:

* cinnamon version
* your pomodoro settings
* exact steps to reproduce, menu options clicked etc for the bug to occur

To make this easier, go to `~/.local/share/cinnamon/applets/pomodoro@gregfreeman.org` and modify

```js
function convertMinutesToSeconds(minutes) {
    return minutes * 60; 
}
```

to

```js
function convertMinutesToSeconds(minutes) {
    return minutes; 
}
```

This will allow you to finish pomodoros in 25 seconds so you can do this process easier.

**Comment by oneeman** [comment]
Just tried this out today and thought I had a similar problem.  After debugging a bit, I realized the count gets incremented after every long break.  Likewise, when autostart is disabled, it autostarts after short breaks, but not after long breaks.

Looking at the code it seems like that's the intended behavior, since the dialog and the increment are set to happen when the queue is finished, not when each break starts or each pomodoro timer stops.  But I find this confusing, since I thought a pomodoro was a 25 minute interval between any breaks, not a group of such intervals between the long breaks.  I'm new to this whole pomodoro system, though.

@gfreeau Any thoughts?

**Comment by oneeman** [comment]
Related to https://github.com/gfreeau/cinnamon-pomodoro/issues/34.  Looking at the wikipedia section referenced there, as well as the pomodoro technique page itself, I believe the correct behavior would be to increment the count after every pomodoro (both short breaks and long breaks) not after every set (only at long breaks).

**Comment by oneeman** [comment]
Just saw https://github.com/gfreeau/cinnamon-pomodoro/pull/35, which I believe addresses this, among other changes.

P.S. sorry for the repeated comments, just noticed the other issue/PR later.
