### ISSUE TITLE
Minutes are not displayed in settings.

### ISSUE THREAD

**Issue by crocket** [gfreeau/cinnamon-pomodoro#67]
![cinnamon_pomodoro_settings](https://cloud.githubusercontent.com/assets/748856/22817750/73392bc6-efac-11e6-8e14-0bbda18441d0.png)

Minutes should be displayed above pomodoro, short break, long break, etc, ...
Since I can't see the minutes, I can't use the timer.

**Comment by gfreeau** [comment]
Thanks for reporting this. What cinnamon version are you using? I am not using the latest release and I can see the minutes.

**Comment by crocket** [comment]
I run cinnamon 3.2.8 on ArchLinux.
I tried Adwaita, Greybird, HighContrast, and Numix themes for controls, but no theme can fix the issue.

**Comment by gfreeau** [comment]
Ok, then there must be an issue with newer versions that needs investigating.

**Comment by ncelerier** [comment]
Hello, 

This is not a problem with this applet. The problem is happening with other applets too. I tried the settings-example applet and it has the problem too: https://github.com/linuxmint/Cinnamon/tree/master/files/usr/share/cinnamon/applets/settings-example%40cinnamon.org.

I'm using Cinnamon 3.2.7. 

I have had a look at the Cinnamon issues but I haven't found anything related to it.

**Comment by gfreeau** [comment]
@ncelerier Thanks for letting me know. I was testing on some older versions and didn't notice the issue.

**Comment by peterchaula** [comment]
@crocket a temporary fix is to replace all `type: 'scale'` is settings-schema.json with the `spinbutton` gtk widget.

**Comment by peterchaula** [comment]
I am having the same issue on Mint 18.1

**Comment by kunnix** [comment]
Yup I have the issue too on Cinnamon 3.2.7 (Mint 18.1)
