### ISSUE TITLE
Change icons.

### ISSUE THREAD

**Issue by m-kru** [gfreeau/cinnamon-pomodoro#73]
Any way to change icons? I don't know why but the red one distracts me.

**Comment by jacckmark** [comment]
Maybe a little late but you can change (at least in new Linux Mint for previous versions you should check docs for info where are installed applets stored) it if you replace the "icon.png" or "icon-break.png" in "/home/YOUR_PC_NAME/.local/share/cinnamon/applets/pomodoro@gregfreeman.org". This way timer will use your icon instead of default one.
Below some smiling face instead of tomato.
![image](https://user-images.githubusercontent.com/26461902/78118432-489c0900-7407-11ea-897e-36a6653795ea.png)
